### ISSUE TITLE
Losing one line after clearing screen

### ISSUE THREAD

**Issue by daniel-mizsak** [dreamsofautonomy/zen-omp#2]
Loved the video and since it looks like that you are a perfectionist when it comes to your terminal I wanted to ask about the "lost" new line at the top of the screen every time you `ctrl + l` or type `clear`. (Or at least I assume you also have this issue?)

It is the byproduct of the `newline = true` of the first block.

I tried getting rid of it by removing the newline from the prompt and adding the extra line [as a zsh hack](https://stackoverflow.com/questions/20512957/zsh-new-line-prompt-after-each-command), but `clear` does not work with that either and hitting `ctrl + c` also uses a lot more lines in the transient prompt.

Do you have any suggestion in mind that might works?

**Comment by daniel-mizsak** [comment]
Ok, I think I figured it out:
There is a [general property of omp](https://ohmyposh.dev/docs/configuration/general) called `enable_cursor_positioning`, from [this issue](https://github.com/JanDeDobbeleer/oh-my-posh/issues/3388).

Just adding this to the configuration already kinda works, but in my case it was only working properly for the `clear` command and not for `ctrl + l`. One could just rebind `ctrl + l` to `clear`, but I ended up [redefining clear](https://superuser.com/questions/1667569/how-can-i-make-clear-preserve-entire-scrollback-buffer) to not clear the scroll back buffer, and bind that to `ctrl + l`.

So in my oh-my-posh toml file I have:
```toml
version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'
enable_cursor_positioning = true

[[blocks]]
  type = 'prompt'

  ...
```

And in my .zshrc:
```bash
alias clear="printf '\033[H\033[2J'"
bindkey -s '^L' 'clear\n'
```

I am currently happy with this, but I appreciate any suggestions for improvements. :)

**Comment by Psypher1** [comment]
@daniel-mizsak following up on this ... Thank you for you suggestion... 

I am using bash, the `clear` works without a hitcth, it's the bindkey thing that seems to not be working for me. Any help you could offer?

**Comment by daniel-mizsak** [comment]
I believe on bash you could try [just `bind`](https://stackoverflow.com/questions/4200800/in-bash-how-do-i-bind-a-function-key-to-a-command).

**Comment by daniel-mizsak** [comment]
I am closing the issue, but unfortunately I did not find an applicable solution.

The main problems with the above mentioned workaround were that:
- If you started to already type in the next command, the bound shortcut will be pasted at the end of it, making it invalid.
- Setting `enable_cursor_positioning = true` can swallow commands as mentioned in [the docs](https://ohmyposh.dev/docs/configuration/block#newline), which for me was a big issue as VSCode were not able to activate python environments for new terminal opens.

So I did lose a line, but at least all the other functionalities seem to work fine.

**Comment by Psypher1** [comment]
> I believe on bash you could try [just `bind`](https://stackoverflow.com/questions/4200800/in-bash-how-do-i-bind-a-function-key-to-a-command).

That worked thank you, had to slightly modify the command for my needs. This works well for me 

```
bind '"\C-l":"clear\n"'
```
